-- set colourscheme
-- local status_ok, color_scheme = pcall(require, "vscode")
-- if not status_ok then
-- 	return
-- end
--
-- color_scheme.setup({
-- 	transparent = false,
-- 	style = "dark",
-- })
--
-- vim.cmd([[colorscheme vscode]])
