-- Neovim init file
require("core/lazy")
require("core/autocmd")
require("core/keymaps")
require("core/colours")
require("core/options")
require("lsp/mason")
-- require("lsp/nvim-jdtls")
require("plugins/conform")
require("lsp/neodev")
require("lsp/lspconfig")
require("plugins/vimtex")
require("plugins/workspaces")
-- require("plugins/nvim-tree")
require("plugins/telescope")
require("plugins/indent-blankline")
require("plugins/nvim-cmp")
require("plugins/nvim-treesitter")
